#!/usr/bin/env bash
# Default compile-profile symbol sets for autogen-pm-ci-profile.sh.

AUTOGEN_PM_CI_BOOL_SYMBOLS=(
    PKG_USING_AUTOGEN_PARAMETER_MANAGER
    RT_USING_MUTEX
    # Cover Kconfig default shell paths when RT-Thread FINSH is available.
    RT_USING_FINSH
    RT_USING_HEAP
    # Required by AUTOGEN_PM_MSH_CMD_SAVE_CLEAN in package Kconfig.
    AUTOGEN_PM_USING_DEBUG
    AUTOGEN_PM_USING_MUTEX
    AUTOGEN_PM_ENABLE_RANGE
    AUTOGEN_PM_ENABLE_NAME
    AUTOGEN_PM_ENABLE_UNIT
    AUTOGEN_PM_ENABLE_DESC
    AUTOGEN_PM_ENABLE_DESC_CHECK
    AUTOGEN_PM_ENABLE_ID
    # Mirror Kconfig defaults selected by the CI NVM profile.
    AUTOGEN_PM_USING_TABLE_ID_CHECK
    AUTOGEN_PM_ENABLE_RUNTIME_TABLE_CHECK
    AUTOGEN_PM_ENABLE_ACCESS
    AUTOGEN_PM_ENABLE_ROLE_POLICY
    AUTOGEN_PM_ENABLE_TYPE_F32
    AUTOGEN_PM_ENABLE_TYPE_OBJECT
    AUTOGEN_PM_ENABLE_TYPE_STR
    AUTOGEN_PM_ENABLE_TYPE_BYTES
    AUTOGEN_PM_ENABLE_TYPE_ARR_U8
    AUTOGEN_PM_ENABLE_TYPE_ARR_U16
    AUTOGEN_PM_ENABLE_TYPE_ARR_U32
    AUTOGEN_PM_ENABLE_RUNTIME_VALIDATION
    AUTOGEN_PM_ENABLE_CHANGE_CALLBACK
    AUTOGEN_PM_ENABLE_RESET_ALL_RAW
    AUTOGEN_PM_USING_NVM
    AUTOGEN_PM_NVM_SCALAR
    AUTOGEN_PM_USING_FLASH_EE_BACKEND
    AUTOGEN_PM_FLASH_EE_PORT_NATIVE
    AUTOGEN_PM_NVM_RECORD_LAYOUT_FIXED_SLOT_WITH_SIZE
    AUTOGEN_PM_USING_MSH_TOOL
    AUTOGEN_PM_MSH_CMD_INFO
    AUTOGEN_PM_MSH_CMD_GET
    AUTOGEN_PM_MSH_CMD_GET_OBJECT
    AUTOGEN_PM_MSH_CMD_SET
    AUTOGEN_PM_MSH_CMD_DEF
    AUTOGEN_PM_MSH_CMD_DEF_ALL
    AUTOGEN_PM_MSH_CMD_SAVE
    AUTOGEN_PM_MSH_CMD_SAVE_CLEAN
    AUTOGEN_PM_MSH_CMD_JSON
)

AUTOGEN_PM_CI_UNSET_SYMBOLS=(
    AUTOGEN_PM_USING_RTT_AT24CXX_BACKEND
    AUTOGEN_PM_FLASH_EE_PORT_FAL
    AUTOGEN_PM_NVM_OBJECT
    AUTOGEN_PM_NVM_OBJECT_STORE_SHARED
    AUTOGEN_PM_NVM_OBJECT_STORE_DEDICATED
    AUTOGEN_PM_NVM_OBJECT_ADDR_AFTER_SCALAR
    AUTOGEN_PM_NVM_OBJECT_ADDR_FIXED
    AUTOGEN_PM_LAYOUT_SOURCE_SCRIPT
    AUTOGEN_PM_ENABLE_GENERATED_INFO
)

AUTOGEN_PM_CI_MANAGED_EXTRA_SYMBOLS=(
    AUTOGEN_PM_NVM_OBJECT_FIXED_ADDR
    AUTOGEN_PM_NVM_OBJECT_REGION_SIZE
    AUTOGEN_PM_NVM_OBJECT_DEDICATED_BASE_ADDR
    AUTOGEN_PM_RTT_AT24_I2C_BUS_NAME
    AUTOGEN_PM_RTT_AT24_ADDR_INPUT
    AUTOGEN_PM_RTT_AT24_BASE_ADDR
    AUTOGEN_PM_RTT_AT24_ERASE_CHUNK
    AUTOGEN_PM_FLASH_EE_FAL_PARTITION_NAME
    AUTOGEN_PM_NVM_WRITE_VERIFY
)

AUTOGEN_PM_CI_NVM_LAYOUT_SYMBOLS=(
    AUTOGEN_PM_NVM_RECORD_LAYOUT_FIXED_SLOT_WITH_SIZE
    AUTOGEN_PM_NVM_RECORD_LAYOUT_FIXED_SLOT_NO_SIZE
    AUTOGEN_PM_NVM_RECORD_LAYOUT_COMPACT_PAYLOAD
    AUTOGEN_PM_NVM_RECORD_LAYOUT_FIXED_PAYLOAD_ONLY
    AUTOGEN_PM_NVM_RECORD_LAYOUT_GROUPED_PAYLOAD_ONLY
)

AUTOGEN_PM_CI_NVM_OBJECT_STORE_SYMBOLS=(
    AUTOGEN_PM_NVM_OBJECT_STORE_SHARED
    AUTOGEN_PM_NVM_OBJECT_STORE_DEDICATED
)

AUTOGEN_PM_CI_NVM_OBJECT_ADDR_SYMBOLS=(
    AUTOGEN_PM_NVM_OBJECT_ADDR_AFTER_SCALAR
    AUTOGEN_PM_NVM_OBJECT_ADDR_FIXED
)

AUTOGEN_PM_CI_BACKEND_SYMBOLS=(
    AUTOGEN_PM_USING_RTT_AT24CXX_BACKEND
    AUTOGEN_PM_USING_FLASH_EE_BACKEND
)

AUTOGEN_PM_CI_FLASH_EE_PORT_SYMBOLS=(
    AUTOGEN_PM_FLASH_EE_PORT_FAL
    AUTOGEN_PM_FLASH_EE_PORT_NATIVE
)

AUTOGEN_PM_CI_VALUE_SYMBOLS=(
    AUTOGEN_PM_MUTEX_TIMEOUT_MS=10
    AUTOGEN_PM_TABLE_ID_SCHEMA_VER=1
    AUTOGEN_PM_FLASH_EE_LOGICAL_SIZE=0x1000
    AUTOGEN_PM_FLASH_EE_CACHE_SIZE=4096
    AUTOGEN_PM_FLASH_EE_LINE_SIZE=32
    AUTOGEN_PM_FLASH_EE_PROGRAM_SIZE=8
)


