#!/usr/bin/env bash
# Host-test target dispatcher.
#
# Keep this list focused on product source, generated-source, and source-tool
# behavior. CI harness self-tests are intentionally out of scope for these
# host-test targets.

host_targets=(
    par_core_runtime
    par_object_runtime
    par_mutex_runtime
    par_shell_tool
    par_shell_feature_gate
    par_nvm_flash_ee
    par_nvm_flash_ee_matrix
    par_nvm_feature_matrix
    par_config_feature_matrix
    par_backend_adapter_smoke
    par_generated_runtime_consistency
)

run_host_targets_parallel() {
    local target
    local pid
    local failed=0
    local pids=()
    local targets=()

    for target in "$@"; do
        targets+=("$target")
        (
            run_host_target "$target"
        ) > "$build_dir/$target.log" 2>&1 &
        pids+=("$!")
    done

    for pid in "${pids[@]}"; do
        if ! wait "$pid"; then
            failed=1
        fi
    done

    for target in "${targets[@]}"; do
        cat "$build_dir/$target.log"
    done
    return "$failed"
}

run_all_host_targets() {
    if [ "${AUTOGEN_PM_HOST_TEST_PARALLEL:-1}" = "0" ]; then
        for target in "${host_targets[@]}"; do
            run_host_target "$target"
        done
    else
        run_host_targets_parallel "${host_targets[@]}"
    fi
}

run_host_target() {
    local target="$1"

    case "$target" in
        par_core_runtime)
            compile_and_run par_core_runtime \
                parameters/tests/host/test_par_core_runtime.c \
                "${base_sources[@]}"
            ;;
        par_object_runtime)
            compile_and_run par_object_runtime \
                parameters/tests/host/test_par_object_runtime.c \
                "${base_sources[@]}"
            ;;
        par_mutex_runtime)
            compile_and_run par_mutex_runtime \
                -DPAR_CFG_MUTEX_EN=1 \
                parameters/tests/host/test_par_mutex_runtime.c \
                "${base_sources[@]}"
            ;;
        par_shell_tool)
            compile_and_run par_shell_tool \
                parameters/tests/host/test_par_shell_tool.c \
                "${base_sources[@]}"
            ;;
        par_shell_feature_gate)
            compile_and_run par_shell_feature_gate \
                -UAUTOGEN_PM_MSH_CMD_INFO \
                -UAUTOGEN_PM_MSH_CMD_GET_OBJECT \
                -UAUTOGEN_PM_MSH_CMD_SET \
                -UAUTOGEN_PM_MSH_CMD_DEF \
                -UAUTOGEN_PM_MSH_CMD_DEF_ALL \
                -UAUTOGEN_PM_MSH_CMD_SAVE \
                -UAUTOGEN_PM_MSH_CMD_SAVE_CLEAN \
                -UAUTOGEN_PM_MSH_CMD_JSON \
                parameters/tests/host/test_par_shell_feature_gate.c \
                "${base_sources[@]}"
            ;;
        par_nvm_flash_ee)
            run_nvm_flash_ee_profile default \
                PAR_CFG_NVM_RECORD_LAYOUT_FIXED_SLOT_WITH_SIZE \
                PAR_CFG_NVM_OBJECT_STORE_SHARED \
                PAR_CFG_NVM_OBJECT_ADDR_FIXED \
                0xC0U 0x40U \
                parameters/src/nvm/scalar/layout/par_nvm_layout_fixed_slot_with_size.c
            ;;
        par_nvm_flash_ee_matrix)
            run_nvm_flash_ee_matrix
            ;;
        par_nvm_feature_matrix)
            bash "$script_dir/nvm-feature-matrix.sh"
            ;;
        par_config_feature_matrix)
            bash "$script_dir/config-feature-matrix.sh"
            ;;
        par_backend_adapter_smoke)
            bash "$script_dir/backend-adapter-smoke.sh"
            ;;
        par_generated_runtime_consistency)
            rm -rf "$build_dir/generated-runtime"
            mkdir -p "$build_dir/generated-runtime/out"
            python3 - "$build_dir/generated-runtime/par_table.generated-runtime.csv" <<'PYGEN'
from pathlib import Path
import csv
import sys

columns = [
    "group", "section", "condition", "enum", "id", "type", "name", "min", "max",
    "default", "unit", "access", "read_roles", "write_roles", "persistent", "desc", "comment",
]
rows = [
    ["GEN", "Scalar", "", "ePAR_GEN_MODE", "0", "U8", "Gen Mode", "0", "10", "2", "", "RW", "ALL", "ALL", "0", "Generated U8 mode.", ""],
    ["GEN", "Scalar", "", "ePAR_GEN_RATE", "1", "U16", "Gen Rate", "0", "1000", "100", "Hz", "RW", "ALL", "ALL", "0", "Generated U16 rate.", ""],
    ["GEN", "Scalar", "", "ePAR_GEN_FLAGS", "2", "U32", "Gen Flags", "0", "65535", "0x10", "", "RW", "ALL", "ALL", "0", "Generated U32 flags.", ""],
    ["GEN", "Object", "", "ePAR_GEN_NAME", "3", "STR", "Gen Name", "0", "8", "ap", "", "RW", "ALL", "ALL", "0", "Generated string object.", ""],
    ["GEN", "Object", "(1 == PAR_CFG_ENABLE_TYPE_BYTES)", "ePAR_GEN_KEY", "4", "BYTES", "Gen Key", "0", "4", "0x01,0x02,0x03", "", "RW", "ALL", "ALL", "0", "Generated bytes object.", ""],
    ["GEN", "Object", "(1 == PAR_CFG_ENABLE_TYPE_ARR_U16)", "ePAR_GEN_ARR16", "6", "ARR_U16", "Gen Arr16", "2", "2", "10,20", "", "RW", "ALL", "ALL", "0", "Generated U16 array object.", ""],
]

dst = Path(sys.argv[1])
with dst.open("w", newline="", encoding="utf-8") as out_file:
    writer = csv.writer(out_file)
    writer.writerow(columns)
    writer.writerows(rows)
PYGEN
            cp parameters/schema/par_id_lock.json \
                "$build_dir/generated-runtime/par_id_lock.json"
            python3 parameters/tools/pargen.py \
                --csv "$build_dir/generated-runtime/par_table.generated-runtime.csv" \
                --id-lock "$build_dir/generated-runtime/par_id_lock.json" \
                --config parameters/schema/pargen.json \
                --out-def "$build_dir/generated-runtime/par_table.def" \
                --out-dir "$build_dir/generated-runtime/out" \
                --manifest "$build_dir/generated-runtime/par_manifest.json"
            echo "[host-tests] build par_generated_runtime_consistency"
            gcc -I"$build_dir/generated-runtime" \
                -I"$build_dir/generated-runtime/out" \
                "${common_cflags[@]}" \
                "${autogen_pm_ci_defines[@]}" \
                -DPAR_CFG_LAYOUT_SOURCE=PAR_CFG_LAYOUT_SCRIPT \
                parameters/tests/host/test_par_generated_runtime_consistency.c \
                "$build_dir/generated-runtime/out/par_layout_static.c" \
                "$build_dir/generated-runtime/out/par_generated_info.c" \
                "${base_sources[@]}" \
                -o "$build_dir/par_generated_runtime_consistency"
            echo "[host-tests] run par_generated_runtime_consistency"
            "$build_dir/par_generated_runtime_consistency"
            ;;
        *)
            echo "Unknown host test target: $target" >&2
            echo "Known targets: ${host_targets[*]}" >&2
            exit 1
            ;;
    esac
}

run_host_targets() {
    local target

    if [ "$#" -eq 0 ]; then
        set -- all
    fi

    for target in "$@"; do
        if [ "$target" = "all" ]; then
            run_all_host_targets
        else
            run_host_target "$target"
        fi
    done
}
