#!/usr/bin/env bash
# Generated-runtime host-test helpers.

# Write the generated-runtime CSV fixture for a named host-test variant.
write_generated_runtime_csv() {
    local variant="$1"
    local dst="$2"

    python3 - "$variant" "$dst" <<'PYGEN'
from pathlib import Path
import csv
import sys

variant = sys.argv[1]
dst = Path(sys.argv[2])
columns = [
    "group", "section", "condition", "enum", "id", "type", "name", "min", "max",
    "default", "unit", "access", "read_roles", "write_roles", "persistent", "desc", "comment",
]
scalar_rows = [
    ["GEN", "Scalar", "", "ePAR_GEN_MODE", "0", "U8", "Gen Mode", "0", "10", "2", "", "RW", "ALL", "ALL", "0", "Generated U8 mode.", ""],
    ["GEN", "Scalar", "", "ePAR_GEN_RATE", "1", "U16", "Gen Rate", "0", "1000", "100", "Hz", "RW", "ALL", "ALL", "0", "Generated U16 rate.", ""],
    ["GEN", "Scalar", "", "ePAR_GEN_FLAGS", "2", "U32", "Gen Flags", "0", "65535", "0x10", "", "RW", "ALL", "ALL", "0", "Generated U32 flags.", ""],
]
object_rows = [
    ["GEN", "Object", "", "ePAR_GEN_NAME", "3", "STR", "Gen Name", "0", "8", "ap", "", "RW", "ALL", "ALL", "0", "Generated string object.", ""],
    ["GEN", "Object", "(1 == PAR_CFG_ENABLE_TYPE_BYTES)", "ePAR_GEN_KEY", "4", "BYTES", "Gen Key", "0", "4", "0x01,0x02,0x03", "", "RW", "ALL", "ALL", "0", "Generated bytes object.", ""],
    ["GEN", "Object", "(1 == PAR_CFG_ENABLE_TYPE_ARR_U8)", "ePAR_GEN_SKIP8", "5", "ARR_U8", "Gen Skip8", "3", "3", "1,2,3", "", "RW", "ALL", "ALL", "0", "Generated U8 array object.", ""],
    ["GEN", "Object", "(1 == PAR_CFG_ENABLE_TYPE_ARR_U16)", "ePAR_GEN_ARR16", "6", "ARR_U16", "Gen Arr16", "2", "2", "10,20", "", "RW", "ALL", "ALL", "0", "Generated U16 array object.", ""],
]

if variant == "scalar-only":
    rows = scalar_rows
elif variant == "condition-disabled":
    rows = scalar_rows + object_rows
    rows[5] = rows[5].copy()
    rows[5][15] = "Generated disabled U8 array object."
elif variant == "consistency":
    rows = scalar_rows + object_rows
else:
    raise SystemExit(f"unsupported generated-runtime variant: {variant}")

with dst.open("w", newline="", encoding="utf-8") as out_file:
    writer = csv.writer(out_file)
    writer.writerow(columns)
    writer.writerows(rows)
PYGEN
}

# Run pargen for one generated-runtime workspace.
run_generated_runtime_pargen() {
    local work_dir="$1"

    cp parameters/schema/par_id_lock.json "$work_dir/par_id_lock.json"
    python3 parameters/tools/pargen.py \
        --csv "$work_dir/par_table.generated-runtime.csv" \
        --id-lock "$work_dir/par_id_lock.json" \
        --config parameters/schema/pargen.json \
        --out-def "$work_dir/par_table.def" \
        --out-dir "$work_dir/out" \
        --manifest "$work_dir/par_manifest.json"
}

# Write manifest-derived compiler defines for generated-runtime tests.
write_generated_runtime_manifest_defines() {
    local manifest_path="$1"
    local output_path="$2"

    python3 - "$manifest_path" > "$output_path" <<'PYMANIFEST'
import json
import sys

manifest = json.load(open(sys.argv[1], encoding="utf-8"))
layout = manifest["layout_max"]
print(f"-DPAR_HOST_TEST_MANIFEST_PARAM_COUNT_MAX={manifest['param_count_max']}U")
print(f"-DPAR_HOST_TEST_MANIFEST_COUNT8={layout['count8']}U")
print(f"-DPAR_HOST_TEST_MANIFEST_COUNT16={layout['count16']}U")
print(f"-DPAR_HOST_TEST_MANIFEST_COUNT32={layout['count32']}U")
print(f"-DPAR_HOST_TEST_MANIFEST_COUNTOBJ={layout['count_obj']}U")
print(f"-DPAR_HOST_TEST_MANIFEST_OBJ_POOL_BYTES={layout['obj_pool_bytes']}UL")
print(f"-DPAR_HOST_TEST_MANIFEST_LAYOUT_SIGNATURE={manifest['layout_signature_max']['signature']}UL")
PYMANIFEST
}

# Compile and run one generated-runtime host target from a generated workspace.
compile_and_run_generated_runtime() {
    local name="$1"
    local work_dir="$2"
    shift 2

    echo "[host-tests] build $name"
    gcc -I"$work_dir" \
        -I"$work_dir/out" \
        "${common_cflags[@]}" \
        "${autogen_pm_ci_defines[@]}" \
        "$@" \
        -DPAR_CFG_LAYOUT_SOURCE=PAR_CFG_LAYOUT_SCRIPT \
        parameters/tests/host/test_par_generated_runtime_consistency.c \
        "$work_dir/out/par_layout_static.c" \
        "$work_dir/out/par_generated_info.c" \
        "${base_sources[@]}" \
        -o "$build_dir/$name"
    echo "[host-tests] run $name"
    "$build_dir/$name"
}

# Run the full generated-runtime consistency target.
run_generated_runtime_consistency_target() {
    local work_dir="$build_dir/generated-runtime"
    local manifest_defines_file="$work_dir/manifest-defines.txt"
    local manifest_defines=()

    rm -rf "$work_dir"
    mkdir -p "$work_dir/out"
    write_generated_runtime_csv consistency "$work_dir/par_table.generated-runtime.csv"
    run_generated_runtime_pargen "$work_dir"
    write_generated_runtime_manifest_defines "$work_dir/par_manifest.json" "$manifest_defines_file"
    mapfile -t manifest_defines < "$manifest_defines_file"
    compile_and_run_generated_runtime par_generated_runtime_consistency \
        "$work_dir" \
        "${manifest_defines[@]}"
}

# Run generated-runtime with condition-disabled object rows.
run_generated_runtime_condition_disabled_target() {
    local work_dir="$build_dir/generated-runtime-condition-disabled"

    rm -rf "$work_dir"
    mkdir -p "$work_dir/out"
    write_generated_runtime_csv condition-disabled "$work_dir/par_table.generated-runtime.csv"
    run_generated_runtime_pargen "$work_dir"
    compile_and_run_generated_runtime par_generated_runtime_condition_disabled \
        "$work_dir" \
        -DPAR_HOST_TEST_GENERATED_CONDITIONAL_DISABLED \
        -DPAR_CFG_ENABLE_TYPE_BYTES=0 \
        -DPAR_CFG_ENABLE_TYPE_ARR_U8=0
}

# Run generated-runtime with scalar rows only.
run_generated_runtime_scalar_only_target() {
    local work_dir="$build_dir/generated-runtime-scalar-only"
    local manifest_defines_file="$work_dir/manifest-defines.txt"
    local manifest_defines=()

    rm -rf "$work_dir"
    mkdir -p "$work_dir/out"
    write_generated_runtime_csv scalar-only "$work_dir/par_table.generated-runtime.csv"
    run_generated_runtime_pargen "$work_dir"
    write_generated_runtime_manifest_defines "$work_dir/par_manifest.json" "$manifest_defines_file"
    mapfile -t manifest_defines < "$manifest_defines_file"
    compile_and_run_generated_runtime par_generated_runtime_scalar_only \
        "$work_dir" \
        "${manifest_defines[@]}" \
        -DPAR_HOST_TEST_GENERATED_SCALAR_ONLY \
        -DPAR_CFG_OBJECT_TYPES_ENABLED=0 \
        -DPAR_CFG_ENABLE_TYPE_STR=0 \
        -DPAR_CFG_ENABLE_TYPE_BYTES=0 \
        -DPAR_CFG_ENABLE_TYPE_ARR_U8=0 \
        -DPAR_CFG_ENABLE_TYPE_ARR_U16=0 \
        -DPAR_CFG_ENABLE_TYPE_ARR_U32=0
}

# Dispatch generated-runtime host-test targets.
run_host_generated_target() {
    local target="$1"

    case "$target" in
        par_generated_runtime_consistency)
            run_generated_runtime_consistency_target
            ;;
        par_generated_runtime_condition_disabled)
            run_generated_runtime_condition_disabled_target
            ;;
        par_generated_runtime_scalar_only)
            run_generated_runtime_scalar_only_target
            ;;
        *)
            return 2
            ;;
    esac
}
