/**
 * @file par_scalar_api.h
 * @brief Declare public scalar-parameter APIs.
 *
 * @copyright Copyright (c) 2026 Ziga Miklosic. Distributed under the MIT license.
 */

#ifndef _PAR_SCALAR_API_H_
#define _PAR_SCALAR_API_H_

#include "par_types.h"

/**
 * @addtogroup PARAMETERS_API
 * @{ <!-- BEGIN GROUP -->
 */

/**
 * @brief Typed parameter setter API.
 */
/**
 * @brief Macro-generated typed API note.
 * @details par_set_u8/i8/u16/i16/u32/i32(/f32), par_set_xxx_fast, and
 * par_get_xxx are generated by macros. Their declarations are listed here,
 * while the implementations are emitted in scalar/par_scalar_api.c through
 * #include "par_typed_impl.inc".
 */
/**
 * @brief Set one scalar parameter from a typed input pointer.
 * @details Object-backed rows do not use this generic setter. Use the dedicated
 * object typed setters instead.
 * @param par_num Parameter number.
 * @param p_val Pointer to the input value.
 * @return Operation status. Returns ePAR_ERROR_TYPE for object rows or ePAR_ERROR_ACCESS when write access is denied.
 */
par_status_t par_set_scalar(const par_num_t par_num, const void *p_val);
/**
 * @brief Set one scalar parameter from a typed input pointer through the unchecked fast path.
 *
 * @note This generic fast setter validates initialization, parameter number,
 * and pointer arguments, then dispatches to the matching typed
 * `par_set_xxx_fast()` implementation.
 *
 * @note It intentionally bypasses access enforcement, runtime validation
 * callbacks, and on-change callbacks. Range limiting still follows
 * the typed fast setter behavior.
 *
 * @note Object-backed rows do not use this generic fast setter.
 *
 * @param par_num Parameter number.
 * @param p_val Pointer to the input value.
 * @return Operation status. Returns ePAR_ERROR_TYPE for object rows.
 */
par_status_t par_set_scalar_fast(const par_num_t par_num, const void *p_val);
#if (1 == PAR_CFG_ENABLE_ID)
/**
 * @brief Set one scalar parameter by external parameter ID.
 * @details Object-backed rows do not use the generic ID-based setter. Use the
 * dedicated object typed setters after resolving the parameter number in the
 * application layer.
 * @param id External parameter ID.
 * @param p_val Pointer to the input value.
 * @return Operation status. Returns ePAR_ERROR_TYPE for object rows or ePAR_ERROR_ACCESS when write access is denied.
 */
par_status_t par_set_scalar_by_id(const uint16_t id, const void *p_val);
#endif /* (1 == PAR_CFG_ENABLE_ID) */
/**
 * @brief Set one U8 parameter.
 * @param par_num Parameter number.
 * @param val U8 value to write.
 * @return Operation status.
 */
par_status_t par_set_u8(const par_num_t par_num, const uint8_t val);
/**
 * @brief Set one I8 parameter.
 * @param par_num Parameter number.
 * @param val I8 value to write.
 * @return Operation status.
 */
par_status_t par_set_i8(const par_num_t par_num, const int8_t val);
/**
 * @brief Set one U16 parameter.
 * @param par_num Parameter number.
 * @param val U16 value to write.
 * @return Operation status.
 */
par_status_t par_set_u16(const par_num_t par_num, const uint16_t val);
/**
 * @brief Set one I16 parameter.
 * @param par_num Parameter number.
 * @param val I16 value to write.
 * @return Operation status.
 */
par_status_t par_set_i16(const par_num_t par_num, const int16_t val);
/**
 * @brief Set one U32 parameter.
 * @param par_num Parameter number.
 * @param val U32 value to write.
 * @return Operation status.
 */
par_status_t par_set_u32(const par_num_t par_num, const uint32_t val);
/**
 * @brief Set one I32 parameter.
 * @param par_num Parameter number.
 * @param val I32 value to write.
 * @return Operation status.
 */
par_status_t par_set_i32(const par_num_t par_num, const int32_t val);
#if (1 == PAR_CFG_ENABLE_TYPE_F32)
/**
 * @brief Set one F32 parameter.
 * @param par_num Parameter number.
 * @param val F32 value to write.
 * @return Operation status.
 */
par_status_t par_set_f32(const par_num_t par_num, const float32_t val);
#endif /* (1 == PAR_CFG_ENABLE_TYPE_F32) */
/**
 * @brief Fast typed setters.
 *
 * @note These APIs are performance-oriented public entry points.
 * Callers must guarantee the module is initialized, par_num is valid,.
 * and the selected typed API matches the parameter type.
 *
 * @note They intentionally bypass access enforcement, runtime validation.
 * callbacks, and on-change callbacks. Range limiting still follows.
 * build-time PAR_CFG_ENABLE_RANGE.
 */
/**
 * @brief Set one U8 parameter through the unchecked fast path.
 * @param par_num Parameter number.
 * @param val U8 value to write.
 * @return Operation status.
 */
par_status_t par_set_u8_fast(const par_num_t par_num, const uint8_t val);
/**
 * @brief Set one I8 parameter through the unchecked fast path.
 * @param par_num Parameter number.
 * @param val I8 value to write.
 * @return Operation status.
 */
par_status_t par_set_i8_fast(const par_num_t par_num, const int8_t val);
/**
 * @brief Set one U16 parameter through the unchecked fast path.
 * @param par_num Parameter number.
 * @param val U16 value to write.
 * @return Operation status.
 */
par_status_t par_set_u16_fast(const par_num_t par_num, const uint16_t val);
/**
 * @brief Set one I16 parameter through the unchecked fast path.
 * @param par_num Parameter number.
 * @param val I16 value to write.
 * @return Operation status.
 */
par_status_t par_set_i16_fast(const par_num_t par_num, const int16_t val);
/**
 * @brief Set one U32 parameter through the unchecked fast path.
 * @param par_num Parameter number.
 * @param val U32 value to write.
 * @return Operation status.
 */
par_status_t par_set_u32_fast(const par_num_t par_num, const uint32_t val);
/**
 * @brief Set one I32 parameter through the unchecked fast path.
 * @param par_num Parameter number.
 * @param val I32 value to write.
 * @return Operation status.
 */
par_status_t par_set_i32_fast(const par_num_t par_num, const int32_t val);
#if (1 == PAR_CFG_ENABLE_TYPE_F32)
/**
 * @brief Set one F32 parameter through the unchecked fast path.
 * @param par_num Parameter number.
 * @param val F32 value to write.
 * @return Operation status.
 */
par_status_t par_set_f32_fast(const par_num_t par_num, const float32_t val);
#endif /* (1 == PAR_CFG_ENABLE_TYPE_F32) */
/**
 * @brief Fast bitwise setters for flags/bitmask parameters.
 *
 * @note These APIs are intended only for U8/U16/U32 parameters that model.
 * flags or bitmasks. They are not a general-purpose replacement for the.
 * normal setter APIs used with ranged numeric values.
 *
 * @note They follow the same trust model as other fast setters: callers must.
 * guarantee the module is initialized, par_num is valid, and the typed.
 * API matches the parameter type.
 *
 * @note They intentionally bypass runtime validation callbacks, on-change.
 * callbacks, and normal setter range semantics.
 */
/**
 * @brief Apply a fast bitwise AND update to one U8 parameter.
 * @param par_num Parameter number.
 * @param val U8 mask value.
 * @return Operation status.
 */
par_status_t par_bitand_set_u8_fast(const par_num_t par_num, const uint8_t val);
/**
 * @brief Apply a fast bitwise AND update to one U16 parameter.
 * @param par_num Parameter number.
 * @param val U16 mask value.
 * @return Operation status.
 */
par_status_t par_bitand_set_u16_fast(const par_num_t par_num, const uint16_t val);
/**
 * @brief Apply a fast bitwise AND update to one U32 parameter.
 * @param par_num Parameter number.
 * @param val U32 mask value.
 * @return Operation status.
 */
par_status_t par_bitand_set_u32_fast(const par_num_t par_num, const uint32_t val);
/**
 * @brief Apply a fast bitwise OR update to one U8 parameter.
 * @param par_num Parameter number.
 * @param val U8 mask value.
 * @return Operation status.
 */
par_status_t par_bitor_set_u8_fast(const par_num_t par_num, const uint8_t val);
/**
 * @brief Apply a fast bitwise OR update to one U16 parameter.
 * @param par_num Parameter number.
 * @param val U16 mask value.
 * @return Operation status.
 */
par_status_t par_bitor_set_u16_fast(const par_num_t par_num, const uint16_t val);
/**
 * @brief Apply a fast bitwise OR update to one U32 parameter.
 * @param par_num Parameter number.
 * @param val U32 mask value.
 * @return Operation status.
 */
par_status_t par_bitor_set_u32_fast(const par_num_t par_num, const uint32_t val);
/**
 * @brief Typed macro wrappers for parameter set.
 */
#define PAR_SET_U8(par_num, value)  par_set_u8((par_num), (value))
#define PAR_SET_I8(par_num, value)  par_set_i8((par_num), (value))
#define PAR_SET_U16(par_num, value) par_set_u16((par_num), (value))
#define PAR_SET_I16(par_num, value) par_set_i16((par_num), (value))
#define PAR_SET_U32(par_num, value) par_set_u32((par_num), (value))
#define PAR_SET_I32(par_num, value) par_set_i32((par_num), (value))
#if (1 == PAR_CFG_ENABLE_TYPE_F32)
#define PAR_SET_F32(par_num, value) par_set_f32((par_num), (value))
#endif /* (1 == PAR_CFG_ENABLE_TYPE_F32) */

/**
 * @brief Getting parameter value API (module must be first initialized before using those func).
 */
/**
 * @brief Read one scalar parameter into a typed output pointer.
 * @details Object-backed rows do not use this generic getter. Use the dedicated
 * object typed getters instead.
 * @param par_num Parameter number.
 * @param p_val Pointer to the output value.
 * @return Operation status. Returns ePAR_ERROR_TYPE for object rows or ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_scalar(const par_num_t par_num, void * const p_val);
#if (1 == PAR_CFG_ENABLE_ID)
/**
 * @brief Read one scalar parameter by external parameter ID.
 * @details Object-backed rows do not use the generic ID-based getter. Use the
 * dedicated object typed getters after resolving the parameter number in the
 * application layer.
 * @param id External parameter ID.
 * @param p_val Pointer to the output value.
 * @return Operation status. Returns ePAR_ERROR_TYPE for object rows or ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_scalar_by_id(const uint16_t id, void * const p_val);
#endif /* (1 == PAR_CFG_ENABLE_ID) */
/**
 * @brief Read one U8 parameter.
 * @param par_num Parameter number.
 * @param p_val Pointer to the U8 output value.
 * @return Operation status. Returns ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_u8(const par_num_t par_num, uint8_t * const p_val);
/**
 * @brief Read one I8 parameter.
 * @param par_num Parameter number.
 * @param p_val Pointer to the I8 output value.
 * @return Operation status. Returns ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_i8(const par_num_t par_num, int8_t * const p_val);
/**
 * @brief Read one U16 parameter.
 * @param par_num Parameter number.
 * @param p_val Pointer to the U16 output value.
 * @return Operation status. Returns ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_u16(const par_num_t par_num, uint16_t * const p_val);
/**
 * @brief Read one I16 parameter.
 * @param par_num Parameter number.
 * @param p_val Pointer to the I16 output value.
 * @return Operation status. Returns ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_i16(const par_num_t par_num, int16_t * const p_val);
/**
 * @brief Read one U32 parameter.
 * @param par_num Parameter number.
 * @param p_val Pointer to the U32 output value.
 * @return Operation status. Returns ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_u32(const par_num_t par_num, uint32_t * const p_val);
/**
 * @brief Read one I32 parameter.
 * @param par_num Parameter number.
 * @param p_val Pointer to the I32 output value.
 * @return Operation status. Returns ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_i32(const par_num_t par_num, int32_t * const p_val);
#if (1 == PAR_CFG_ENABLE_TYPE_F32)
/**
 * @brief Read one F32 parameter.
 * @param par_num Parameter number.
 * @param p_val Pointer to the F32 output value.
 * @return Operation status. Returns ePAR_ERROR_ACCESS when read access is denied.
 */
par_status_t par_get_f32(const par_num_t par_num, float32_t * const p_val);
#endif /* (1 == PAR_CFG_ENABLE_TYPE_F32) */
/**
 * @brief Read the configured default value for one parameter.
 * @param par_num Parameter number.
 * @param p_val Pointer to the output value.
 * @return Operation status.
 */
par_status_t par_get_scalar_default(const par_num_t par_num, void * const p_val);

/** @} <!-- END GROUP --> */

#endif /* !defined(_PAR_SCALAR_API_H_) */
